(ns utsushi.pipeline.h264-mp4-test
  "Golden-vector, end-to-end test for `utsushi.pipeline.h264-mp4` — the
   ENCODE-direction mirror of `utsushi.pipeline.mp4-h264-test`: raw pixels
   → real H.264 encode → real avc1/avcC MP4 mux → a real, independent
   `ffmpeg` can decode it. Matches ADR-2606272200 / ADR-2607122000 Phase 1
   \"R0.5\"'s integration-proof discipline, encode direction.

   `resources/utsushi/fixtures/h264-mp4-encode-flat32.mp4` and
   `h264-mp4-encode-chroma-multimb32.mp4` were generated by THIS
   namespace's own `encode-frame->mp4` (not ffmpeg/x264 — see each
   deftest below for the exact source pixel arrays, which are
   reproduced byte-for-byte here so the test regenerates the identical
   MP4 on every run rather than trusting a static blob) and checked in
   both for provenance and so a human can re-verify with real ffmpeg by
   hand:

     ffmpeg -i h264-mp4-encode-flat32.mp4 -pix_fmt yuv420p out.yuv

   `*.ref.yuv` is the SAME file decoded once by a real `ffmpeg 8.1.1`
   (2026-07) — ffmpeg's own reconstructed pixels are ground truth.
   Comparison below is bit-exact, no tolerance, and (for the flat fixture)
   also bit-exact against the ORIGINAL pre-encode source pixels (a flat
   16x16-aligned macroblock has zero AC residual at any legal QP, so
   Intra_16x16 DC-only H.264 encode/decode is lossless for it — the same
   property `org-iso-h264`'s own `flat-multi-mb-roundtrip-bit-exact` test
   relies on)."
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.java.io :as io]
            [h264.encode :as h264-encode]
            [isobmff.demux :as demux]
            [utsushi.codec :as codec]
            [utsushi.pipeline.h264-mp4 :as encode-pipeline]
            [utsushi.pipeline.mp4-h264 :as decode-pipeline]))

(defn- rd-bytes [p]
  (mapv #(bit-and (int %) 0xff) (with-open [in (io/input-stream (io/resource p))] (.readAllBytes in))))

;; ---- fixture A: flat luma, default (flat 128) chroma — lossless case ----

(def ^:private flat-w 32)
(def ^:private flat-h 32)
(def ^:private flat-luma (vec (repeat (* flat-w flat-h) 100)))

(deftest encode-frame->mp4-flat32-real-ffmpeg-golden-vector
  (let [mp4-bytes (encode-pipeline/encode-frame->mp4 {:width flat-w :height flat-h :qp 24 :luma flat-luma})
        ref (rd-bytes "utsushi/fixtures/h264-mp4-encode-flat32.ref.yuv")
        ref-luma (vec (take (* flat-w flat-h) ref))
        ref-cb   (vec (subvec ref (* flat-w flat-h) (+ (* flat-w flat-h) (* 16 16))))
        ref-cr   (vec (subvec ref (+ (* flat-w flat-h) (* 16 16)) (+ (* flat-w flat-h) (* 2 16 16))))]
    (testing "byte-identical to the checked-in fixture MP4 (deterministic regeneration)"
      (is (= (rd-bytes "utsushi/fixtures/h264-mp4-encode-flat32.mp4") mp4-bytes)))
    (testing "real ffmpeg decodes this MP4's luma bit-exact vs the ORIGINAL source pixels (lossless: flat content needs zero AC residual)"
      (is (= flat-luma ref-luma)))
    (testing "real ffmpeg decodes this MP4's chroma bit-exact vs h264.encode's documented flat-128 default (no :cb/:cr given)"
      (is (= (repeat (* 16 16) 128) ref-cb))
      (is (= (repeat (* 16 16) 128) ref-cr)))
    (testing "our OWN decode pipeline (utsushi.pipeline.mp4-h264) reading back this exact MP4 also matches ffmpeg exactly"
      (let [self-decoded (decode-pipeline/decode-first-h264-frame mp4-bytes)]
        (is (= flat-w (:width self-decoded)))
        (is (= flat-h (:height self-decoded)))
        (is (= ref-luma (:luma self-decoded)))))))

;; ---- fixture B: flat luma + REAL oscillating Cb/Cr — exercises real
;;      chroma AC residual + avcC/avc1 round trip through both real
;;      ffmpeg AND this repo's own decode pipeline on the identical file
;;      (mirrors org-iso-h264's own chroma-multimb-realac-roundtrip-
;;      bounded-error test's source pattern, applied end-to-end through a
;;      real MP4 container instead of a bare Annex B stream) ----

(def ^:private cmb-w 32)
(def ^:private cmb-h 32)
(def ^:private cmb-luma (vec (repeat (* cmb-w cmb-h) 100)))
(def ^:private cmb-cb (vec (for [r (range 16) c (range 16)]
                              (int (+ 128 (* 40 (Math/sin (/ c 2.0)) (Math/cos (/ r 3.0))))))))
(def ^:private cmb-cr (vec (for [r (range 16) c (range 16)]
                              (int (+ 128 (* 40 (Math/cos (/ c 3.0)) (Math/sin (/ r 2.0))))))))

(deftest encode-frame->mp4-chroma-multimb32-real-ffmpeg-golden-vector
  (let [mp4-bytes (encode-pipeline/encode-frame->mp4
                   {:width cmb-w :height cmb-h :qp 20 :luma cmb-luma :cb cmb-cb :cr cmb-cr})
        ref (rd-bytes "utsushi/fixtures/h264-mp4-encode-chroma-multimb32.ref.yuv")
        ref-luma (vec (take (* cmb-w cmb-h) ref))
        ref-cb   (vec (subvec ref (* cmb-w cmb-h) (+ (* cmb-w cmb-h) (* 16 16))))
        ref-cr   (vec (subvec ref (+ (* cmb-w cmb-h) (* 16 16)) (+ (* cmb-w cmb-h) (* 2 16 16))))]
    (testing "byte-identical to the checked-in fixture MP4 (deterministic regeneration)"
      (is (= (rd-bytes "utsushi/fixtures/h264-mp4-encode-chroma-multimb32.mp4") mp4-bytes)))
    (testing "real ffmpeg decodes this MP4's luma bit-exact vs the ORIGINAL source pixels (flat luma, still lossless)"
      (is (= cmb-luma ref-luma)))
    (testing "real chroma AC residual actually happened (ffmpeg's chroma output isn't degenerate/flat)"
      (is (> (count (distinct ref-cb)) 1))
      (is (> (count (distinct ref-cr)) 1)))
    (testing "our OWN decode pipeline reading back this exact MP4 is bit-exact vs real ffmpeg's decode of the SAME file, luma AND chroma (the strongest available correctness signal for lossy chroma content: not the pre-encode source, but agreement between two independent decoders on the identical real container+bitstream)"
      (let [self-decoded (decode-pipeline/decode-first-h264-frame mp4-bytes)]
        (is (= cmb-w (:width self-decoded)))
        (is (= cmb-h (:height self-decoded)))
        (is (= ref-luma (:luma self-decoded)))
        (is (= ref-cb (:cb self-decoded)))
        (is (= ref-cr (:cr self-decoded)))))))

;; ---- unit-level tests for the box-building helpers ----

(deftest nalus->avcc-sample-length-prefixes-each-nal
  (testing "each NAL gets its own 4-byte big-endian length prefix, no start codes"
    (let [nal-a [0x65 0xAA 0xBB]
          nal-b [0x41 0xCC]
          avcc (encode-pipeline/nalus->avcc-sample [nal-a nal-b] 4)]
      (is (= (vec (concat [0 0 0 3] nal-a [0 0 0 2] nal-b)) avcc)))))

(deftest annexb->param-and-slice-nalus-splits-real-encode-output
  (testing "a real h264.encode Annex B stream splits into exactly one SPS, one PPS, one IDR slice"
    (let [{:keys [bytes]} (h264-encode/encode-idr-luma-frame
                           {:width 16 :height 16 :qp 26 :luma (vec (repeat 256 128))})
          {:keys [sps-nalu pps-nalu slice-nalus]} (encode-pipeline/annexb->param-and-slice-nalus bytes)]
      (is (= 7 (bit-and (first sps-nalu) 0x1f)) "SPS NAL unit type")
      (is (= 8 (bit-and (first pps-nalu) 0x1f)) "PPS NAL unit type")
      (is (= 1 (count slice-nalus)))
      (is (= 5 (bit-and (first (first slice-nalus)) 0x1f)) "IDR slice NAL unit type"))))

(deftest avcc-payload-embeds-real-profile-level-from-sps
  (testing "avcC's AVCProfileIndication/AVCLevelIndication are read directly off the real SPS NALU bytes, not re-derived"
    (let [{:keys [bytes]} (h264-encode/encode-idr-luma-frame
                           {:width 16 :height 16 :qp 26 :luma (vec (repeat 256 128))})
          {:keys [sps-nalu pps-nalu]} (encode-pipeline/annexb->param-and-slice-nalus bytes)
          avcc (encode-pipeline/avcc-payload sps-nalu pps-nalu)]
      (is (= 1 (nth avcc 0)) "configurationVersion")
      (is (= 66 (nth avcc 1)) "AVCProfileIndication (baseline, matches h264.encode's hardcoded profile-idc)")
      (is (= 30 (nth avcc 3)) "AVCLevelIndication (matches h264.encode's hardcoded level-idc)")
      (is (= 0xFF (nth avcc 4)) "lengthSizeMinusOne byte (reserved bits all 1 + lengthSizeMinusOne=3)"))))

(deftest h264-encode-decode-mp4-round-trip-preserved-through-avcc-config
  (testing "utsushi.codec's EXISTING avcC reader (find-avcc/avcc-config) can parse the stsd THIS namespace writes — cross-namespace shape agreement, not just self-consistency"
    (let [mp4-bytes (encode-pipeline/encode-frame->mp4 {:width 16 :height 16 :qp 26 :luma (vec (repeat 256 128))})
          demuxed (demux/demux mp4-bytes)
          track (first (filter #(= (:handler %) "vide") (:tracks demuxed)))
          avcc (codec/find-avcc (:stsd track))
          cfg (codec/avcc-config avcc)]
      (is (= 4 (:length-size cfg)))
      (is (= 1 (count (:sps-nalus cfg))))
      (is (= 1 (count (:pps-nalus cfg)))))))
